version: "3.9"
services:
  public-service:
    build:
      context: ./public-service
    ports:
      - "3000:3000"
    networks:
      - app-network

  private-service:
    build:
      context: ./private-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  apigateway:
    build:
      context: ./apigateway
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
